Update Auth.swift
kinde-oss/kinde-sdk-ios pull request #17
Opened 2024-07-16 11:44 UTC by wahabniazi56

# Explain your changes

_Suppose there is a related issue with enough detail for a reviewer to understand your changes fully. In that case, you can omit an explanation and instead include either “Fixes #XX” or “Updates #XX” where “XX” is the issue number._

# Checklist

- [ ] I have read the [“Pull requests” section](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md#pull-requests) in the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md).
- [ ] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md).

🛟 _If you need help, consider asking for advice over in the [Kinde community](https://thekindecommunity.slack.com)._

2024-07-17 07:42 UTC, onderay requested changes
@wahabniazi56 please provide a description to your PR as per the guidelines https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CONTRIBUTING.md#pull-requests

2024-07-17 11:41 UTC, wahabniazi56 commented
@onderay I just edit description of this PR please review that if its not enough so please guide me how to do that or give me any sample description of PR. I try to explain everything which I added in this update but if still something missing let me know I will update accordingly. Thanks

2024-07-18 22:39 UTC, DanielRivers approved these changes

2024-07-23 07:41 UTC, onderay approved these changes

2024-07-23 07:42 UTC, merged